name: flutter_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.2
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  flutter_tts: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/bg.jpg
    - lib/assets/bg1.jpg
    - lib/assets/logo.png
    - lib/assets/bg2.png

  uses-material-design: true
